name: ktlint Check

on:
  pull_request:
    branches: [ develop ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "base.url=${{ secrets.BASE_URL }}" >> local.properties
          echo "kakao.native.app.key=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> local.properties

      - name: Run ktlint check
        run: ./gradlew ktlintCheck
